use std::env;
use std::fs;
use std::path::Path;

fn main() {
    embuild::espidf::sysenv::output();
    generate_secrets_config();
}

fn generate_secrets_config() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let secrets_path = Path::new(&manifest_dir).join("secrets.toml");
    let example_path = Path::new(&manifest_dir).join("secrets.example.toml");

    let toml_str = fs::read_to_string(&secrets_path).unwrap_or_else(|_| {
        fs::read_to_string(&example_path).expect("secrets.example.toml must exist")
    });

    let table: toml::Table = toml::from_str(&toml_str).expect("invalid secrets TOML");

    let get_str = |key: &str, default: &str| -> String {
        table
            .get(key)
            .and_then(|v| v.as_str())
            .unwrap_or(default)
            .to_string()
    };

    let transcription_provider = get_str("transcription_provider", "openai");
    let openai_key = get_str("openai_key", "");
    let cursor_api_key = get_str("cursor_api_key", "");
    let base_host = table
        .get("transcription_base_host")
        .and_then(|v| v.as_str())
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty());

    let cfg = zoop_core::TranscriptionConfig::from_secrets(
        &transcription_provider,
        &openai_key,
        &cursor_api_key,
        base_host.as_deref(),
    )
    .unwrap_or_else(|e| {
        panic!(
            "invalid transcription config in secrets.toml (provider={transcription_provider}): {e:?}"
        );
    });

    let wifi_ssid = get_str("wifi_ssid", "YOUR_WIFI_SSID");
    let wifi_pass = get_str("wifi_pass", "YOUR_WIFI_PASSWORD");
    let local_time_offset_min: i32 = table
        .get("local_time_offset_min")
        .and_then(|v| v.as_integer())
        .unwrap_or(0) as i32;

    let out = format!(
        r#"// @generated by firmware/build.rs — do not edit
pub const WIFI_SSID: &str = {wifi_ssid:?};
pub const WIFI_PASS: &str = {wifi_pass:?};
pub const LOCAL_TIME_OFFSET_MIN: i32 = {local_time_offset_min};
pub const TRANSCRIPTION_PROVIDER: &str = {provider:?};
pub const TRANSCRIPTION_HOST: &str = {host:?};
pub const TRANSCRIPTION_PATH: &str = {path:?};
pub const TRANSCRIPTION_API_KEY: &str = {api_key:?};
pub const TRANSCRIPTION_MODEL: &str = {model:?};
pub const TRANSCRIPTION_BOUNDARY: &str = {boundary:?};
"#,
        wifi_ssid = wifi_ssid,
        wifi_pass = wifi_pass,
        provider = cfg.provider.as_str(),
        host = cfg.host,
        path = cfg.path,
        api_key = cfg.api_key,
        model = cfg.model,
        boundary = cfg.boundary,
    );

    fs::write(Path::new(&out_dir).join("secrets_config.rs"), out).expect("write secrets_config.rs");
}
